paths:
  raw_data: "data/raw/dirty_cafe_sales.csv" -- Пусть к исходному файлу с необработанными данными
  processed_data: "data/processed/clean_cafe_sales.csv" -- Путь к файлу с очищенными данными
  output_plots: "data/output/plots" -- Путь к папке с графиками в формате png, jpg

logs:
  level: "INFO"
  file: "logs/etl.log"